/* Copyright 2024 The TensorFlow Authors. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================*/

// =============================================================================
// C++ symbolic-gradient registration for FlashAttentionForward.
// This is consumed by tensorflow::AddSymbolicGradients (cc/framework/gradients).
// Python (tf.GradientTape / tf.gradients) goes through a separate registry and
// is intentionally NOT registered here.
//
// Forward: FlashAttentionForward(q, k, v, mask) -> (O, L)
//   - O is the attention output, L is the per-row logsumexp scratch
//     (kept as a real output so the backward can reuse it without recomputation).
//
// Backward: FlashAttentionBackward(q, k, v, mask, O, dO, L) -> (dQ, dK, dV)
//
// Gradient mapping:
//   grad_inputs[0] = dO  (upstream gradient of O)
//   grad_inputs[1] = dL  (upstream gradient of L; ALWAYS dropped - L is internal)
//   grad_outputs   = [dQ, dK, dV, NoGradient()]   // last entry is for `mask`
// =============================================================================

#include "tensorflow/cc/framework/grad_op_registry.h"
#include "tensorflow/cc/framework/gradients.h"
#include "tensorflow/cc/ops/flash_attn_ops.h"  // generated by tf_gen_op_wrapper_cc
#include "tensorflow/core/lib/core/errors.h"

namespace tensorflow {
namespace ops {
namespace {

// Gradient of FlashAttentionForward
Status FlashAttentionForwardGrad(const Scope& scope, const Operation& op,
                                 const std::vector<Output>& grad_inputs,
                                 std::vector<Output>* grad_outputs) {
  // ==== Defensive arity checks (invariants enforced by the op schema) ====
  if (op.num_inputs() != 4) {
    return errors::Internal(
        "FlashAttentionForward gradient: expected 4 inputs (q, k, v, mask), "
        "got ", op.num_inputs());
  }
  if (op.num_outputs() != 2) {
    return errors::Internal(
        "FlashAttentionForward gradient: expected 2 outputs (output, "
        "logsumexp), got ", op.num_outputs());
  }
  if (grad_inputs.size() != 2) {
    return errors::Internal(
        "FlashAttentionForward gradient: expected 2 grad_inputs "
        "(dO, dL), got ", grad_inputs.size());
  }

  // ==== Build the backward op ====
  // Inputs:  q, k, v, mask, O, dO, L
  // Outputs: dQ, dK, dV
  //
  // grad_inputs[1] (dL) is intentionally ignored: L is an internal scratch
  // output and any user that backprops through it has misused the API.
  auto bwd = FlashAttentionBackward(
      scope.WithOpName("FlashAttentionGrad"),
      op.input(0),     // q
      op.input(1),     // k
      op.input(2),     // v
      op.input(3),     // mask
      op.output(0),    // O
      grad_inputs[0],  // dO
      op.output(1));   // L (logsumexp)

  TF_RETURN_IF_ERROR(scope.status());
  
  // ==== Wire gradients back to the 4 forward inputs ====
  grad_outputs->push_back(bwd.grad_q);
  grad_outputs->push_back(bwd.grad_k);
  grad_outputs->push_back(bwd.grad_v);
  grad_outputs->push_back(NoGradient());  // mask: not differentiable

  return scope.status();
}

REGISTER_GRADIENT_OP("FlashAttentionForward", FlashAttentionForwardGrad);

// FlashAttentionBackward is itself not differentiable (no 2nd-order support).
// Mark it explicitly so AddSymbolicGradients fails fast with a clear message
// instead of silently emitting a malformed graph.
REGISTER_NO_GRADIENT_OP("FlashAttentionBackward");

}  // namespace
}  // namespace ops
}  // namespace tensorflow
