# Generated by patches/patch_manager.py from patches/manifest.json.
# Do not edit this file directly.

load("//tensorflow/patch_features:kdnn_copts.bzl", "kdnn_copts")

def boostsra_feature_copt():
    return (
        kdnn_copts() +
        []
    )
